const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Orbit,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Follow,
		C3.Behaviors.custom,
		C3.Behaviors.Car,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.wrap,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.LOS,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.destroy,
		C3.Behaviors.bound,
		C3.Behaviors.Anchor,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Persist,
		C3.Behaviors.NoSave,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Metro: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{BrownBlock: 0},
	{Sprite2: 0},
	{Sine: 0},
	{Rotate: 0},
	{Physics: 0},
	{Pathfinding: 0},
	{Orbit: 0},
	{MoveTo: 0},
	{Follow: 0},
	{Custom: 0},
	{Car: 0},
	{Bullet: 0},
	{"8Direction": 0},
	{Wrap: 0},
	{Tween: 0},
	{Timer: 0},
	{Pin: 0},
	{LineOfSight: 0},
	{Flash: 0},
	{Fade: 0},
	{DragDrop: 0},
	{DestroyOutsideLayout: 0},
	{BoundToLayout: 0},
	{Anchor: 0},
	{ShadowCaster: 0},
	{Persist: 0},
	{NoSave: 0},
	{Sprite3: 0},
	{BlueBlock: 0},
	{RedBlock: 0},
	{Sprite4: 0},
	{NxtDoor: 0},
	{Text: 0},
	{start: 0},
	{Mouse: 0},
	{Gameover: 0},
	{menu: 0},
	{NewLevels: 0},
	{MainBg: 0},
	{StartPage: 0},
	{EndPage: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Metro: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	BrownBlock: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BlueBlock: class extends self.ITiledBackgroundInstance {},
	RedBlock: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	NxtDoor: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	start: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Gameover: class extends self.ITextInstance {},
	menu: class extends self.ITextInstance {},
	NewLevels: class extends self.ITextInstance {},
	MainBg: class extends self.ISpriteInstance {},
	StartPage: class extends self.ISpriteInstance {},
	EndPage: class extends self.ISpriteInstance {}
}